### ISSUE TITLE
[Core] Get rid of auto value class and replace with kotlin

### ISSUE THREAD

**Issue by noorejannat** [amardeshbd/android-daily-headlines#187] opened 2018-02-14 03:37 UTC
AutoValue is no longer required as kotlin data class does the job.
As part of task, should introduce kotlin to tablet module [OPTIONAL, or leave it for historical purpose].

**Comment by amardeshbd** [comment] 2018-02-17 21:09
This may be duplicate of #195

**Comment by amardeshbd** [comment] 2018-02-25 04:27
Fixed in https://github.com/amardeshbd/android-daily-headlines/issues/195

**Closed by amardeshbd** 2018-02-25 04:27 UTC
Labels: enhancement, maintenance
